// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallTool'](arg1, arg2, arg3);
}

export function ConnectServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectServer'](arg1, arg2, arg3, arg4);
}

export function DisconnectServer(arg1) {
  return window['go']['main']['App']['DisconnectServer'](arg1);
}

export function FormatResult(arg1) {
  return window['go']['main']['App']['FormatResult'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListTools(arg1) {
  return window['go']['main']['App']['ListTools'](arg1);
}
