// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hub} from '../models';

export function CallTool(arg1:string,arg2:string,arg3:Record<string, any>):Promise<hub.CallResult>;

export function ConnectServer(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<void>;

export function DisconnectServer(arg1:string):Promise<void>;

export function FormatResult(arg1:hub.CallResult):Promise<string>;

export function ListServers():Promise<Array<hub.ServerInfo>>;

export function ListTools(arg1:string):Promise<Array<hub.ToolInfo>>;
